### ISSUE TITLE
Plot Unit Waveforms hangs for long time

### ISSUE THREAD

**Issue by McD-NMI** [SpikeInterface/spikewidgets#45]
I am having issue trying to use a couple of the spikewidgets plotting functions after sorting. 
Namely: **plot_unit_wavforms()** and **plot_amplitudes_distribution()**. They seem to hang for an awfully long time, at least 30min before I cancelled. 

Below is what I am calling: 

```
sw.plot_unit_waveforms(recording, sorting, max_spikes_per_unit=100)

sw.plot_amplitudes_distribution(recording_f, sorting_circus_split, max_spikes_per_unit=100)
```

I have also tried **st.postprocessing.get_unit_waveforms()** and while this works, it seems to take a very long time per waveform, at least compared to running it a few weeks ago.

**Comment by alejoe91** [comment]
Hi @McD-NMI 

How long is your recording? and how many channels? do you use the filter before sorting? 

If you use the `preprocessing.bandpass_filter` I recommend adding the argument `cache_to_file=True`. This filters the entire recording once and dumps it to a file for fast access. If this is not done, due to the lazy operation, everytime a new waveform is accessed the snippet is filtered, which is very slow.

Can you check if this is the problem?

**Comment by McD-NMI** [comment]
That seems to have solved the issue, thanks so much @alejoe91 !
